# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20170720_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('currency', models.CharField(max_length=16)),
                ('ask', models.FloatField()),
                ('bid', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('open', models.FloatField()),
            ],
        ),
    ]
