# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_dealmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealmodel',
            name='sell_or_buy',
            field=models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], max_length=16, null=True),
        ),
    ]
