# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_dealmodel_sell_or_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealmodel',
            name='open_or_closed',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], max_length=16, null=True),
        ),
    ]
