# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_dealmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
