# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealmodel',
            name='date_close',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
