# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_dealmodel_date_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
